### ISSUE TITLE
`Cannot get /` when declaring root

### ISSUE THREAD

**Issue by johnsonjo4531** [egojump/peco#26]
Hey I really enjoy Peco your static site generator so far. I know it's in beta, but I seem to be running into an issue. When I declare the `root` to for example '/blog/' in my peco.config.yml and run `peco dev` the site at http://localhost:4000/ only displays 'Cannot get /'. If I go to http://localhost:4000/blog/ it instead says, 'Cannot get /blog/'. Also am I supposed to be hard coding in the `/blog/` into the links to my post, because the `root` option doesn't seem to be showing up in the paths to the articles.

If you can't recreate the issue I can post the link to my github repo for my Peco blog. Thanks.

**Comment by egoist** [comment]
Fixed in v0.1.8, the website is always served at root path `/` during development

**Comment by johnsonjo4531** [comment]
Thanks egoist that is very helpful. I'm new to Vue router, and wasn't sure I needed to use it in Peco for links and routing. Also thanks again for Peco!
