### ISSUE TITLE
Add documentation: How to scaffold

### ISSUE THREAD

**Issue by asifm** [egojump/peco#27]
Peco looks great. Thanks for making this.

I'm having difficulty understanding how to scaffold my blog. I couldn't find anywhere a proper documentation of the sequence of commands or actions I'm supposed to perform to get started.

**Comment by egoist** [comment]
I just created a tool for this: https://github.com/egojump/pecoup

**Comment by asifm** [comment]
Fantastic. I went through the whole process. Everything went smoothly. And you did it so quickly!

How do you say *pecoup*?

`pecoup new post "title of post"` seems to have some problem. I'll add an issue to pecoup's repo.
